[package]
name = "wasm"
version = "0.1.0"
edition = "2021"

[lib]
path="src/lib.rs"
crate-type=["cdylib"]

[dependencies]
mycelial-crdt = "0.2.2"
wasm-bindgen = "0.2"
js-sys = "0.3"
serde_json = "1"
console_error_panic_hook = "0.1.7"
serde = "1"

[dev-dependencies]
wasm-bindgen-test = "0.3"

[profile.release]
lto = true
